name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [ 12.22.7 ]
        abi: [ arm ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup 32-bit dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq build-essential gcc-multilib g++-multilib
    - name: Set Android NDK
      run: echo "::set-env name=ANDROID_NDK_HOME::$ANDROID_SDK_ROOT/ndk-bundle"

    - name: Build
      run: ANDROID_ABI=${{matrix.abi}} ./build.sh build-android ${{matrix.node}}
    
    - uses: actions/upload-artifact@v2
      with:
        name: lib-android-${{matrix.node}}-${{matrix.abi}}
        path: node-${{matrix.node}}/out/Release/lib.target